global:
  scrape_interval:     10s # By default, scrape targets every 15 seconds.
  evaluation_interval: 10s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'Cloud dashboard'

scrape_configs:
  - job_name: 'monies'
    scrape_interval: 5s
    static_configs:
      - targets: ['monies:8080']
