global:
  scrape_interval:     10s # By default, scrape targets every 15 seconds.
  evaluation_interval: 10s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'Cloud dashboard'

scrape_configs:
  - job_name: 'monies'
    scrape_interval: 5s
    static_configs:
      - targets: ['monies:8080']

  - job_name: 'netdata'
    metrics_path: /api/v1/allmetrics
    scrape_interval: 5s
    params:
      format: [ prometheus ]
    static_configs:
        - targets: ['netdata:19999']
