global:
  scrape_interval:     10s # By default, scrape targets every 15 seconds.
  evaluation_interval: 10s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'Hub dashboard'

scrape_configs:
  - job_name: 'monies'
    scrape_interval: 5s
    static_configs:
      - targets: ['monies:8080']

  - job_name: 'hub'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100', 'cadvisor:8080']

  - job_name: 'scraparr'
    static_configs:
      - targets: [ 'scraparr:7100' ]
