version: "3.9"

networks:
  docker-direct:
    external: true

services:
  hoarder:
    image: ghcr.io/hoarder-app/hoarder:latest
    container_name: hoarder
    restart: unless-stopped
    networks:
      - docker-direct
    volumes:
      - $DATA_DIR/hoarder/data:/data
    environment:
      - MEILI_ADDR=http://meilisearch:7700
      - BROWSER_WEB_URL=http://chrome:9222
      - OPENAI_API_KEY
      - DATA_DIR=/data
      - NEXTAUTH_SECRET
      - NEXTAUTH_URL=https://hoarder.hub
      - MEILI_MASTER_KEY
    labels:
      caddy: hoarder.hub
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 3000}}"

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:latest
    container_name: chrome
    restart: unless-stopped
    networks:
      - docker-direct
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    restart: unless-stopped
    networks:
      - docker-direct
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY
    volumes:
      - $DATA_DIR/meilisearch/data:/meili_data
