version: '3.8'

networks:
  docker-direct:
    external: true

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    user: $PUID:$PGID
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    command: --cleanup --interval=3600
    networks:
      - docker-direct
    environment:
      - WATCHTOWER_NO_STARTUP_MESSAGE=true
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM
      - WATCHTOWER_NOTIFICATION_EMAIL_TO
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.11.1
    restart: unless-stopped
    user: $PUID:$PGID
    # https://github.com/portainer/portainer/issues/3092
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $DATA_DIR/portainer:/data
    networks:
      - docker-direct
    labels:
      caddy: portainer.hub
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 9000}}"

#  timemachine:
#    image: mbentley/timemachine:smb
#    container_name: timemachine
#    environment:
#      - TM_USERNAME=${SMB_USER}
#      - PASSWORD=${SMB_PASS}
#      - SET_PERMISSIONS=true
#      - TM_UID=${PUID}
#      - TM_GID=${PGID}
#      - SMB_INHERIT_PERMISSIONS=yes
#      - DEBUG_LEVEL=3
#      - WORKGROUP=Hub
#    restart: unless-stopped
#    networks:
#      docker-direct:
#        ipv4_address: 10.10.2.253
#    volumes:
#      - ${HUB_DIR}/time-machine/${SMB_USER}:/opt/${SMB_USER}
#    ulimits:
#      nofile:
#        soft: 65536
#        hard: 65536

#  samba:
#    container_name: samba
#    image: ghcr.io/jtagcat/samba:latest
#    restart: unless-stopped
#    environment:
#      - TZ
#    networks:
#      docker-direct:
#        ipv4_address: 10.10.2.253
#    read_only: true
#    tmpfs:
#      - /tmp
#    stdin_open: true
#    tty: true
#    volumes:
#      - ${HUB_DIR}/time-machine:/backup
#    command: [ "-s", "TimeMachineBackup;/backup/${SMB_USER};yes;no;no;${SMB_USER},smbuser;${SMB_USER},smbuser;${SMB_USER},smbuser",
#               "-u", "${SMB_USER};${SMB_PASS};${PUID};;${PGID}",
#               "-g", "log level = 2",
#               "-g", "fruit:metadata = stream"
#              ]

  samba:
    image: vedhavyas/samba:latest
    container_name: samba
    restart: unless-stopped
    volumes:
      - ${CONF_DIR}/smb.conf:/etc/samba/smb.conf
      - ${HUB_DIR}/time-machine:/home
    environment:
      - TZ
      - PUID
      - PGID
      - SMB_USER
      - SMB_PASS
    networks:
      docker-direct:
        ipv4_address: 10.10.2.253
