version: "3.9"

networks:
  docker-direct:
    external: true

services:
  subspace-devnet-node:
    image: ghcr.io/subspace/node:snapshot-2023-oct-25
    volumes:
      - $DATA_DIR/Subspace/devnet/node:/var/subspace:rw
    networks:
      - docker-direct
    user: $PUID:$PGID
    restart: unless-stopped
    command: [
      "--chain", "devnet",
      "--base-path", "/var/subspace",
      "--port", "30333",
      "--name", "invincible",
    ]
    healthcheck:
      timeout: 5s
      interval: 30s
      retries: 5
