version: "3.9"

networks:
  docker-direct:
    external: true
  docker-direct-static:
    external: true

services:
  immich-server:
    container_name: immich_server
    hostname: immich_server
    image: ghcr.io/immich-app/immich-server:release
    restart: unless-stopped
    command: [ "start.sh", "immich" ]
    networks:
      # have to use static ip since the android app
      # built with flutter http client doesn't support self-signed yet
      # https://github.com/immich-app/immich/issues/765
      docker-direct-static:
        ipv4_address: 10.10.2.8
    volumes:
      - $HUB_DIR/media/photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ${CONF_DIR}/immich.conf
    environment:
      - NODE_ENV=production
      - JWT_SECRET=IMMICH_JWT_SECRET
    depends_on:
      - immich-redis
      - immich-postgres
    labels:
      caddy: photos.hub
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 3001}}"

  immich-microservices:
    container_name: immich_microservices
    hostname: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "microservices" ]
    networks:
      - docker-direct
    volumes:
      - $HUB_DIR/media/photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ${CONF_DIR}/immich.conf
    environment:
      - NODE_ENV=production
      - JWT_SECRET=IMMICH_JWT_SECRET
    depends_on:
      - immich-redis
      - immich-postgres
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    hostname: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    networks:
      - docker-direct
    volumes:
      - $HUB_DIR/media/photos:/usr/src/app/upload
      - $DATA_DIR/immich/model_cache/:/cache
    env_file:
      - ${CONF_DIR}/immich.conf
    environment:
      - NODE_ENV=production
      - JWT_SECRET=IMMICH_JWT_SECRET
    depends_on:
      - immich-postgres
    restart: unless-stopped

  immich-redis:
    container_name: immich_redis
    hostname: immich_redis
    image: redis:6.2
    restart: unless-stopped
    volumes:
      - $DATA_DIR/immich/redis/:/data
    networks:
      - docker-direct

  immich-postgres:
    container_name: immich_postgres
    hostname: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    networks:
      - docker-direct
    environment:
      POSTGRES_PASSWORD: immich
      POSTGRES_USER: immich
      POSTGRES_DB: immich
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - $DATA_DIR/immich/postgres:/var/lib/postgresql/data
    restart: unless-stopped
