version: "3.9"

networks:
  docker-direct:
    external: true

services:
  calender:
    image: 'bloben/app:latest'
    container_name: calender
    networks:
      - docker-direct
    restart: unless-stopped
    environment:
      - APP_DOMAIN=calender.$DOMAIN
    env_file:
      - $CONF_DIR/bloben.env
    labels:
      caddy: calender.hub
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 80}}"

  calender-db:
    image: 'postgres:14'
    container_name: calender-db
    env_file:
      - $CONF_DIR/bloben.env
    volumes:
      - $DATA_DIR/bloben/db:/var/lib/postgresql/data
    networks:
      - docker-direct
    restart: unless-stopped

  calender-redis:
    image: redis:7
    container_name: calender-redis
    volumes:
      - $DATA_DIR/bloben/redis:/data
    restart: unless-stopped
    networks:
      - docker-direct
