version: "3.9"

networks:
  docker-direct:
    external: true
  docker-vpn:
    external: true

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    hostname: watchtower
    user: $PUID:$PGID
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    command: --cleanup --interval=3600
    networks:
      - docker-direct
    environment:
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=Hub
      - WATCHTOWER_NO_STARTUP_MESSAGE=true
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
      - WATCHTOWER_NOTIFICATIONS=email gotify
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM
      - WATCHTOWER_NOTIFICATION_EMAIL_TO
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=http://notifier:80
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN
      - WATCHTOWER_NOTIFICATION_GOTIFY_TLS_SKIP_VERIFY=true

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.11.1
    restart: unless-stopped
    hostname: portainer
    user: $PUID:$PGID
    # https://github.com/portainer/portainer/issues/3092
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $DATA_DIR/portainer:/data
    networks:
      - docker-direct
    labels:
      caddy: portainer.hub
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 9000}}"

  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    hostname: librespeed
    networks:
      - docker-direct
      - docker-vpn
    environment:
      - PUID
      - PGID
      - TZ
      - PASSWORD=librespeed
      - CUSTOM_RESULTS=true
      - DB_TYPE=sqlite
    volumes:
      - $DATA_DIR/librespeed:/config
    restart: unless-stopped
    labels:
      caddy: fast.hub
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 80}}"
