version: "3.9"

networks:
  docker-direct:
    external: true
  docker-vpn:
    external: true

services:
  notifier:
    container_name: notifier
    image: gotify/server:latest
    restart: unless-stopped
    hostname: notifier
    networks:
      - docker-direct
      - docker-vpn
    environment:
      - GOTIFY_DEFAULTUSER_NAME
      - GOTIFY_DEFAULTUSER_PASS
    volumes:
      - "${DATA_DIR}/gotify:/app/data"
    labels:
      caddy: notifier.hub
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 80}}"

  rss:
    container_name: rss
    image: lscr.io/linuxserver/freshrss:latest
    restart: unless-stopped
    hostname: rss
    networks:
      - docker-vpn
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - "${DATA_DIR}/freshrss/data:/config"
      # Optional volume for storing third-party extensions
      - "${DATA_DIR}/freshrss/extensions:/config/www/freshrss/extensions"
    labels:
      caddy: rss.hub
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 80}}"

  pairdrop:
    image: lscr.io/linuxserver/pairdrop:latest
    container_name: pairdrop
    hostname: pairdrop
    restart: unless-stopped
    environment:
      - PUID
      - PGID
      - TZ
      - WS_FALLBACK=true
      - DEBUG_MODE=true
    networks:
      - docker-direct
    labels:
      caddy: pairdrop.hub
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 3000}}"
