version: "3.9"

networks:
  docker-direct:
    external: true

services:
  gemini-1b-archive-node:
    container_name: gemini-1b-archive-node
    image: ghcr.io/nazar-pc/node:gemini-1b-pre-release
    volumes:
      - /var/subspace/gemini-1b/archive-node:/var/subspace:rw
    user: $PUID:$PGID
    networks:
      docker-direct:
        ipv4_address: 10.10.2.253
    restart: unless-stopped
    command: [
      "--chain", "gemini-1",
      "--base-path", "/var/subspace",
      "--execution", "wasm",
      "--pruning", "archive",
      "--keep-blocks", "1024",
      "--port", "30333",
#      "--rpc-cors", "all",
#      "--rpc-methods", "safe",
#      "--validator",
      "--name", "mandalorian",
      "--bootnodes", "/ip4/176.122.88.128/tcp/30334/p2p/12D3KooWPhmm8MV8EciomUyKrquHznPXWpSHcJAhWG1x2DHYwpZk",
      "--bootnodes", "/ip4/176.122.88.128/tcp/30335/p2p/12D3KooWEWmUX8futkbi8YodaRGFuuuxyngmKWDPazVob4JwT1TE",
    ]
    healthcheck:
      timeout: 5s
      interval: 30s
      retries: 5

#  gemini-1b-farmer:
#    depends_on:
#      gemini-1b-node:
#        condition: service_healthy
#    container_name: gemini-1b-farmer
#    image: ghcr.io/nazar-pc/farmer:gemini-1b-pre-release
#    user: $PUID:$PGID
#    networks:
#      - docker-direct
#    volumes:
#      - /var/subspace/node:/var/subspace:rw
#    restart: unless-stopped
#    command: [
#      "--base-path", "/var/subspace",
#      "farm",
#      "--node-rpc-url", "ws://gemini-1b-node:9944",
#      "--ws-server-listen-addr", "0.0.0.0:9955",
#      "--reward-address", "${SUBSPACE_WALLET_ADDRESS}",
#      "--plot-size", "150G"
#    ]
#
