version: "3.9"

networks:
  docker-direct:
    external: true

volumes:
  node-data:
  farmer-data:

services:
  gemini-1b-node:
    container_name: gemini-1b-node
    image: ghcr.io/nazar-pc/node:gemini-1b-pre-release
    volumes:
      - node-data:/var/subspace:rw
    networks:
      docker-direct:
        ipv4_address: 10.10.1.253
    restart: unless-stopped
    command: [
      "--chain", "gemini-1",
      "--base-path", "/var/subspace",
      "--execution", "wasm",
      "--pruning", "1024",
      "--keep-blocks", "1024",
      "--port", "30333",
      "--rpc-cors", "all",
      "--rpc-methods", "safe",
      "--unsafe-ws-external",
      "--validator",
      "--name", "mandalorian"
    ]
    healthcheck:
      timeout: 5s
      interval: 30s
      retries: 5

  gemini-1b-farmer:
    depends_on:
      node:
        condition: service_healthy
    container_name: gemini-1b-farmer
    image: ghcr.io/nazar-pc/farmer:gemini-1b-pre-release
    networks:
      - docker-direct
    volumes:
      - farmer-data:/var/subspace:rw
    restart: unless-stopped
    command: [
      "--base-path", "/var/subspace",
      "farm",
      "--node-rpc-url", "ws://node:9944",
      "--ws-server-listen-addr", "0.0.0.0:9955",
      "--reward-address", "${SUBSPACE_WALLET_ADDRESS}",
      "--plot-size", "150G"
    ]

