version: '3.8'

networks:
  docker-vpn:
    # https://chris.heald.me/2018/docker-default-routes/
    # cant use docker direct network for all except monies
    # since docker defaults to lexico sort to get default network when multiple are passed
    # it will always pick docker-direct over docker-vpn
    # so using vpn network for all containers
    external: true

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    user: $PUID:$PGID
    networks:
      - docker-vpn
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    restart: unless-stopped
    networks:
      - docker-vpn
    logging:
      options:
        max-size: 1g

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    user: $PUID:$PGID
    networks:
      - docker-vpn
    volumes:
      - $CONF_DIR/prometheus.yml:/etc/prometheus/prometheus.yml
      - $DATA_DIR/prometheus/data:/prometheus
    command:
      - '--web.enable-admin-api'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=180d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    labels:
      caddy: prometheus.hub
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 9090}}"

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    restart: unless-stopped
    user: $PUID:$PGID
    networks:
      - docker-vpn
    volumes:
      - $CONF_DIR/grafana_datasource.yml:/etc/grafana/provisioning/datasource.yml
      - $DATA_DIR/grafana/data/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_USERS_ALLOW_SIGN_UP=false
    labels:
      caddy: grafana.hub
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 3000}}"

  monies:
    image: vedhavyas/monies:latest
    container_name: monies
    restart: unless-stopped
    user: $PUID:$PGID
    environment:
      - ZERODHA_USERNAME
      - ZERODHA_PWD
      - ZERODHA_2FA_CODE
      - LIVE_COIN_WATCH_API_KEY
    networks:
      - docker-vpn
