FROM tomsquest/docker-radicale:latest

RUN python3 -m pip install git+https://github.com/Unrud/RadicaleIMAP --break-system-packages
RUN python3 -m pip install git+https://github.com/Unrud/RadicaleInfCloud --break-system-packages
