# Workflow builds docker images of libs and pushes images to docker hub
on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  workflow_dispatch:
  push:
name: Build
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        build: [mullvad, radicale, webdav, media-cleaner, archiver]
    runs-on: ${{ matrix.os }}
    env:
      DOCKER_USERNAME: ${{ secrets.docker_username }}
      DOCKER_PASSWORD: ${{ secrets.docker_password }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install zsh
        run: sudo apt-get update; sudo apt-get install zsh
      - name: Build docker images
        run: ./libs/docker.sh build ${{ matrix.build }}
      - name: Push images to Docker Hub
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          ./libs/docker.sh push ${{ matrix.build }}
